### ISSUE TITLE
Stopped working in Chrome as well

### ISSUE THREAD

**Issue by Yahav** [jsantell/dancer.js#57]
Dance.js is not working anymore neither in Chrome:
Uncaught TypeError: undefined is not a function dancer.js:32.
This makes it completely unusable.

**Comment by Yahav** [comment]
Just found a solution:

SEARCH FOR: 
this.context.createGainNode
REPLACE WITH:
this.context.createGain

SEARCH FOR: 
this.context.createJavaScriptNode
REPLACE WITH:
this.context.createScriptProcessor

**Comment by ottonascarella** [comment]
Not working on Chrome 36.0.1985.125 m

JS Errors:

Uncaught TypeError: undefined is not a function jsantell.github.io/dancer.js/dancer.js:354

Uncaught TypeError: Failed to execute 'connect' on 'AudioNode': No function was found that matched the signature provided. dancer.js:321

**Comment by altmind** [comment]
I can confirm @ottonascarella. Web example does not work in chrome 36. Gives error:

Uncaught TypeError: Failed to execute 'connect' on 'AudioNode': No function was found that matched the signature provided. dancer.js:321
